config/routes.rb
Rails.application.routes.draw do
  
  root 'flows#index'
  get 'data', to: 'flows#data'
  get 'generate', to: 'flows#generate'

end

app/models/flow.rb
class Flow < ActiveRecord::Base

#associations
#none

#gems
#none

#validations
  validates :time, :flowrate, presence: true

#callbacks
#none

#methods

  def self.generate_data
    Flow.create(time: Time.now, flowrate: generate_diurnal_data * rand() )
  end


  def self.generate_diurnal_data

    if  0 < Time.now.strftime("%H").to_i && Time.now.strftime("%H").to_i <= 4
      1

    elsif 4 < Time.now.strftime("%H").to_i && Time.now.strftime("%H").to_i <= 8
      50 

    elsif 8 < Time.now.strftime("%H").to_i && Time.now.strftime("%H").to_i <= 12
      30

    elsif 12 < Time.now.strftime("%H").to_i && Time.now.strftime("%H").to_i <= 16
      15
    
    elsif 16 < Time.now.strftime("%H").to_i && Time.now.strftime("%H").to_i <= 20
      30

    elsif 20 < Time.now.strftime("%H").to_i && Time.now.strftime("%H").to_i <= 24
      50 

    else
      1
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  
  def index
    @flows = Flow.order(time: :desc)    
  end

  def data
    @chart_data = Flow.order(time: :desc) 

    respond_to do |format|
      format.html
      format.json
    end
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/views/flows/data.html.haml
<h1>Flows#data</h1>
<p>Find me in app/views/flows/data.html.erb</p>

app/views/flows/data.json.erb
{
  "cols": [{"id": "datetime", "label": "DateTime", "type": "datetime"},
        {"id": "flow", "label": "flow", "type": "number"}],
 
  "rows":[ <% @chart_data.each do |data| %>
  {"c": [{"v":"Date(<%= data.time.strftime("%s%L") %>)"}, {"v": <%= data.flowrate %>}]}<%= data.id == @chart_data.last.id ? " " : "," %>
<% end %>
  ]
}

app/views/flows/index.html.haml
.row
  .small-12.large-12.columns
    %h1
      Full Stack Developer - Interval Web App 
    %h4
      by Ely Greenberg ( #{mail_to "ergreenberg@gmail.com", "ergreenberg@gmail.com"} ), submitted on September 22, 2014.

    %hr

    #chart_div

    %br
    %br
    %br
    %hr

.row
  .small-12.large-6.columns 
    %table
      %thead 
        %tr
          %th.text-center Time
          %th.text-center Flow (gallons per hour)
      %tbody
        -@flows.each do |f|
          %tr
            %td.text-center= f.time
            %td.text-center= f.flowrate
  
  .small-12.large-6.columns
    %p Notes
    %ul
      %li
        This is an ROR web-app that displays fictitious flow data from a water meter. Water flows are typically diurnal, and the flowrates are randomly generated using a rake function that runs every hour. After the rake function completes the data (time and flowrate) that is generated are saved to the database. 
      %li 
        JSON data is available at #{link_to "data.json", data_path(format: :json) }
      %li
        The annotation chart is from the Google Charts API. 
      %li
        The front-end, albeit sparse, is built using the Foundation framework. 
      %li
        There are a few simple tests that can be run with <kbd> rspec spec </kbd> on the command line
      %li
        Files are available on my GitHub account, #{link_to "https://github.com/elygreenberg/water_flow_interval_web_app", "https://github.com/elygreenberg/water_flow_interval_web_app"}

   
  %br
  %br
  %br


%script{type:"text/javascript", src:"https://www.google.com/jsapi"}

:javascript
  google.load('visualization', '1.1', {'packages':['annotationchart']});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var jsonData = $.ajax({
    url: "../data.json",
    dataType:"json",
    async: false
    }).responseText;

    var annotation_data = new google.visualization.DataTable(jsonData);
    
    console.log(jsonData)

    var chart = new google.visualization.AnnotationChart(document.getElementById('chart_div'));

    var options = {
      displayAnnotations: true
    };

    chart.draw(annotation_data, options);
  } 

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Full Stack Developer - Interval Web App by Ely Greenberg"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    %br
    = yield
    %br
    %br
    %br

    = javascript_include_tag "application"